apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceAccount.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceAccount.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: operator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["kopf", "run", "/operator/main.py", "--all-namespaces"]