apiVersion: ops.io/v1
kind: ScheduledTask
metadata:
  name: hello-world
  namespace: default
spec:
  schedule: "*/1 * * * *"
  image: busybox
  command: ["echo", "operator just reconciled this change"]
  suspended: false
  jitter: 0